### ISSUE TITLE
build a conda environment file for this work

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/qs-web2023#7]
With the growing list of additional packages to run this software, it would help to create a [custom conda environment file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) to provide the full list of packages.

_Originally posted by @prjemian in https://github.com/BCDA-APS/qs-web2023/issues/5#issuecomment-1578907953_

**Comment by prjemian** [comment]
Here is an example (and starting point): https://github.com/BCDA-APS/bluesky_training/blob/main/bluesky/environments/environment_2023_2.yml

**Comment by prjemian** [comment]
Start a list of additional packages (or changes) as comments here.  We'll use that to update the environment.

**Comment by samaraaugust** [comment]
- uvicorn
- bluesky_httpserver

**Comment by prjemian** [comment]
Any more packages for this?  (such as `npm`)?

**Comment by prjemian** [comment]
I'll work this up in a branch for review later today.  Good starting point from the [gemviz](https://github.com/BCDA-APS/gemviz/blob/main/env.yml) repo.

**Comment by prjemian** [comment]
`env.yml` from gemviz:

```yaml
name: gemviz23

# conda env create --force -n gemviz23 -f ./env.yml --solver=libmamba

channels:
  - conda-forge
  - defaults

dependencies:
  - tiled
  - pyqt =5
  - qt =5
```
